name: Quality
on:
  - push
  - pull_request
jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}
      - uses: github/codeql-action/init@v1
      - uses: github/codeql-action/autobuild@v1
      - uses: github/codeql-action/analyze@v1
